### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by Mr-ZhuJun** [qherau/3DGS-Calib#1]
Hello:
       Another great work. You have just published the use of nerf for driverless calibration and 3DGS for sensor calibration. You are the author who has the fastest application of the latest technology I have seen so far. I would like to ask if the method you proposed has been used. It runs on Huawei's in-vehicle system. I would like to communicate with you privately. I don't know if there is any relevant contact information.

**Comment by qherau** [comment]
Hi,
Thank you for your comments on my work. We can have further discussions by email: quentin.herau@gmail.com.
